apiVersion: apps/v1
kind: Deployment
metadata:
  name: dana-frontend
  labels:
    app: dana-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dana-frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: dana-frontend
    spec:
      containers:
      - name: dana-frontend
        image: ${DOCKER_IMAGE_URL}:${DANA_VERSION}
        args: ["npm", "run", "start:frontend"]
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 20
          periodSeconds: 10
        env:
        - name: NODE_ENV
          value: "production"
        - name: API_URL
          value: "https://api.dana-ai.com"
---
apiVersion: v1
kind: Service
metadata:
  name: dana-frontend-service
spec:
  selector:
    app: dana-frontend
  ports:
  - port: 80
    targetPort: 3000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dana-frontend-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "30"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - dana-ai.com
    - www.dana-ai.com
    secretName: dana-ai-tls
  rules:
  - host: dana-ai.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dana-frontend-service
            port:
              number: 80
  - host: www.dana-ai.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dana-frontend-service
            port:
              number: 80