apiVersion: apps/v1
kind: Deployment
metadata:
  name: dana-ai-app
  labels:
    app: dana-ai
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dana-ai
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: dana-ai
    spec:
      containers:
      - name: dana-ai-app
        image: ${ECR_REPOSITORY_URL}:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        envFrom:
        - secretRef:
            name: dana-ai-secrets
        - configMapRef:
            name: dana-ai-config