apiVersion: v1
kind: Secret
metadata:
  name: dana-ai-secrets
type: Opaque
stringData:
  # Database credentials
  DATABASE_URL: "postgresql://postgres:postgres@db:5432/dana_db"
  PGDATABASE: "dana_db"
  PGHOST: "db"
  PGPORT: "5432"
  PGUSER: "postgres"
  PGPASSWORD: "postgres"
  
  # Authentication
  SESSION_SECRET: "${SESSION_SECRET}"
  JWT_SECRET: "${JWT_SECRET}"
  REPL_ID: "${REPL_ID}"
  
  # OAuth secrets
  FACEBOOK_APP_ID: "${FACEBOOK_APP_ID}"
  FACEBOOK_APP_SECRET: "${FACEBOOK_APP_SECRET}"
  GOOGLE_OAUTH_CLIENT_ID: "${GOOGLE_OAUTH_CLIENT_ID}"
  GOOGLE_OAUTH_CLIENT_SECRET: "${GOOGLE_OAUTH_CLIENT_SECRET}"
  
  # Slack integration
  SLACK_BOT_TOKEN: "${SLACK_BOT_TOKEN}"
  SLACK_CHANNEL_ID: "${SLACK_CHANNEL_ID}"
  
  # Email and notifications
  SENDGRID_API_KEY: "${SENDGRID_API_KEY}"
  
  # AI services
  OPENAI_API_KEY: "${OPENAI_API_KEY}"
  
  # Notion integration
  NOTION_INTEGRATION_SECRET: "${NOTION_INTEGRATION_SECRET}"
  NOTION_PAGE_URL: "${NOTION_PAGE_URL}"
  
  # CRM integration
  HUBSPOT_CLIENT_ID: "${HUBSPOT_CLIENT_ID}"
  HUBSPOT_CLIENT_SECRET: "${HUBSPOT_CLIENT_SECRET}"
  SALESFORCE_CLIENT_ID: "${SALESFORCE_CLIENT_ID}"
  SALESFORCE_CLIENT_SECRET: "${SALESFORCE_CLIENT_SECRET}"